# Generated by Django 2.2.3 on 2020-03-30 19:39

import broadcasts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_target', models.IntegerField(choices=[(1, 'All users'), (2, 'Anonymous or unauthenticated users only'), (3, 'Authenticated users only')], default=1, verbose_name='user target')),
                ('url_target', models.TextField(default='.*', help_text='Uses regular expressions to match target URLs. <br/><br />\n            Special Characters:<br />\n            <code>"*"</code> is a wildcard, it matches anything.<br />\n            <code>"|"</code> symbolizes an "OR" condition, either this or that.<br />\n            <code>"$"</code> signifies a hard stop, matching paths must end at the "$".<br />\n            <code>"?"</code> makes preceding character optional.<br /><br />\n            Examples:<br />\n            <code>.*</code> applies to entire site. <br/>\n            <code>/path/to/this/$</code> matches that specific path only. <br/>\n            <code>/path/to/this/$|/path/to/that$</code> matches either\n            <code>/path/to/this/</code> OR <code>/path/to/that</code>\n            <br/><code>/anything/beneath/this/</code> matches any path that starts with\n            <code>/anything/beneath/this/</code><br />\n            <code>/anything/here/?</code> matches any path starting with\n            <code>/anything/here/</code> OR <code>/anything/here</code><br /><br />', verbose_name='url target')),
                ('title', models.CharField(default='(No Title)', max_length=50, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, default=broadcasts.models.one_year, null=True, verbose_name='end time')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('show_frequency', models.IntegerField(choices=[(1, 'Show this message only once'), (2, 'Show this message once per visit'), (3, 'Always show this message')], default=1, verbose_name='show frequency')),
                ('message_type', models.CharField(blank=True, default='top-banner', max_length=50, verbose_name='message type')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
            ],
            options={
                'ordering': ['-end_time'],
            },
        ),
    ]
