# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-16 16:08


from django.db import migrations, models


def set_blank_message_types(apps, schema_editor):
    # The default value for message type is changing from blank to top-banner.
    # Update existing data to reflect this change.
    BroadcastMessage = apps.get_model("broadcasts", "BroadcastMessage")  # NOQA
    for message in BroadcastMessage.objects.filter(message_type=''):
        message.message_type = 'top-banner'
        message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='message_type',
            field=models.CharField(blank=True, choices=[('top-banner', 'Top-of-Page Banner'), ('javascript', 'Javascript')], default=b'top-banner', max_length=50, verbose_name='message type'),
        ),
        migrations.RunPython(
            set_blank_message_types
        ),
    ]
