# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-02 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0002_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='url_target',
            field=models.TextField(default=b'.*', help_text='Uses regular expressions to match target URLs. <br/>\n            <code>.*</code> applies to entire site. <br/>\n            <code>/path/to/this.html</code> matches that specific path. <br/>\n            <code>/path/to/this.html|/or/to/this.html</code> matches either\n            <code>/path/to/this.html</code> OR <code>/or/to/this.html</code>\n            <br/><code>/anything/under/.*</code> matches any path starting with\n            <code>/anything/under/</code><br />\n            <code>/anything/here/?</code> matches any path starting with\n            <code>/anything/here/</code> OR <code>/anything/here</code><br />\n            ("?" makes preceding character optional)', verbose_name='url target'),
        ),
    ]
